config/routes.rb
 Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
      }
  resources :techwords, only: [:index, :show]
  resources :articles do
    member do
      get :download_article_pdf
    end
  end
  get 'home/index'
  root 'home#index'

  namespace :admins do
    resources :techwords
    resources :categories
    resources :articles do
        resources :article_notes
    end
  end

  post "comments/create_article_comments" => "comments#create_article_comments"
  post "comments/create_techword_comments" => "comments#create_techword_comments"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, uniqueness: true,
                            length: {minimum: 3}
  validates :description, presence: true
  belongs_to :category, optional: true
  has_many :article_notes
  has_many :comments, as: :commentable
  belongs_to :user, optional: true
end

app/controllers/admins/articles_controller.rb
class Admins::ArticlesController < ApplicationController
  load_and_authorize_resource
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to admins_article_path(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to admins_article_path(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admins_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :category_id, :user_id)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show,:download_article_pdf]

  def index
     @articles = Article.all
  end

  def download_article_pdf

  end


  def show

  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/download_article_pdf.html.erb
<p id="pdf_link"><%= link_to "Download Article now", download_article_pdf_article_path(@article, :format => "pdf"),class: "btn btn-primary btn-lg"%></p>



<div class="well">
  <h2 class="text-center"><%= @article.title %></h2>
</div>
<div>
  <h2><%= @article.description.html_safe %></h2>
</div>

app/views/articles/index.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Definition</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to article.title, article_path(article) %></td>
          <td><%= article.description.html_safe %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/articles/show.html.erb
<%= link_to "Download Invoice (PDF)", download_article_pdf_article_path(@article)%>


  <%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @article.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @article.description.html_safe %></dd>
</dl>

<%= link_to "Back", root_path, class: "btn btn-primary" %>

<% if @article.article_notes.present? %>
<div class="well">
  <h2 class="text-center">Notes</h2>
</div>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% @article.article_notes.each do |note| %>
  <div class="panel panel-info">
    <div class="panel-heading" role="tab" id="heading_<%= note.id %>">
      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse_<%= note.id%>" aria-expanded="false" aria-controls="collapse_<%= note.id%>">
        <h4 class="panel-title">
          <%= note.question %>
        </h4>
      </a>
    </div>
    <div id="collapse_<%= note.id%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_<%= note.id %>">
      <div class="panel-body">
        <%= note.answer.html_safe %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

<% if @article.comments.present? %>
<div class="well">
  <h1 class="text-center">Comments</h1>
</div>
<% @article.comments.each do |comment|%>
  <p>
    <strong><%= comment.user.email %> says</strong>: <%= comment.comment_text %>
  </p>
  <p><strong>on</strong>: <%= comment.created_at.strftime("%b-%d-%Y") %></p>
  <%end %>
<%end if @article.comments.present? %>

<div class="well">
  <h1 class="text-center">Add new Comment</h1>
</div>

<%= render "comments/new_article_comment"%>