config/routes.rb
 Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
      }
  resources :techwords, only: [:index, :show]
  resources :articles do
    member do
      get :download_article_pdf
    end
  end
  get 'home/index'
  root 'home#index'

  namespace :admins do
    resources :techwords
    resources :categories
    resources :articles do
        resources :article_notes
    end
  end

  post "comments/create_article_comments" => "comments#create_article_comments"
  post "comments/create_techword_comments" => "comments#create_techword_comments"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/techword.rb
class Techword < ApplicationRecord
  has_many :comments, as: :commentable
  belongs_to :user, optional: true
end

app/controllers/admins/techwords_controller.rb
class Admins::TechwordsController < ApplicationController
  before_action :set_techword, only: [:show, :edit, :update, :destroy]

  # GET /techwords
  # GET /techwords.json
  def index
    #@techwords = Techword.all
     @q = Techword.ransack(params[:q])
     @techwords = @q.result(distinct: true)
  end

  # GET /techwords/1
  # GET /techwords/1.json
  def show
  end

  # GET /techwords/new
  def new
    @techword = Techword.new
  end

  # GET /techwords/1/edit
  def edit
  end

  # POST /techwords
  # POST /techwords.json
  def create
    @techword = Techword.new(techword_params)

    respond_to do |format|
      if @techword.save
        format.html { redirect_to admins_techword_path(@techword), notice: 'Techword was successfully created.' }
        format.json { render :show, status: :created, location: @techword }
      else
        format.html { render :new }
        format.json { render json: @techword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /techwords/1
  # PATCH/PUT /techwords/1.json
  def update
    respond_to do |format|
      if @techword.update(techword_params)
        format.html { redirect_to admins_techword_path(@techword), notice: 'Techword was successfully updated.' }
        format.json { render :show, status: :ok, location: @techword }
      else
        format.html { render :edit }
        format.json { render json: @techword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /techwords/1
  # DELETE /techwords/1.json
  def destroy
    @techword.destroy
    respond_to do |format|
      format.html { redirect_to admins_techwords_url, notice: 'Techword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_techword
      @techword = Techword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def techword_params
      params.require(:techword).permit(:name, :definition, :user_id)
    end
end

app/controllers/techwords_controller.rb
class TechwordsController < ApplicationController
  before_action :set_techword, only: [:show, :edit, :update, :destroy]

  def index
     @q = Techword.ransack(params[:q])
     @techwords = @q.result(distinct: true)
  end

  def show
  end

  private

    def set_techword
      @techword = Techword.find(params[:id])
    end

end

app/helpers/techwords_helper.rb
module TechwordsHelper
end

app/views/techwords/index.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Definition</th>
      </tr>
    </thead>
    <tbody>
      <% @techwords.each do |techword| %>
        <tr>
          <td><%= link_to techword.name, techword_path(techword) %></td>
          <td><%= techword.definition.html_safe %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/techwords/show.html.erb
<div class="well">
  <h1 class="text-center"><%= @techword.name %></h1>
</div>

<%= @techword.definition.html_safe %>
<div class="well">
  <h1 class="text-center">Comments</h1>
</div>

<%= render "comments/new_techword_comment"%>

<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>

<% if @techword.comments.present? %>
<div class="well">
  <h1 class="text-center">Comments posted by users</h1>
</div>
<% @techword.comments.each do |comment|%>
  <p>
    <strong><%= comment.user.email %> says</strong>: <%= comment.comment_text %>
  </p>
  <p><strong>on</strong>: <%= comment.created_at.strftime("%b-%d-%Y") %></p>
  <%end%>
<%end%>