config/routes.rb
 Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
      }
  resources :techwords, only: [:index, :show]
  resources :articles do
    member do
      get :download_article_pdf
    end
  end
  get 'home/index'
  root 'home#index'

  namespace :admins do
    resources :techwords
    resources :categories
    resources :articles do
        resources :article_notes
    end
  end

  post "comments/create_article_comments" => "comments#create_article_comments"
  post "comments/create_techword_comments" => "comments#create_techword_comments"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, uniqueness: true,
                            length: {minimum: 3}
  validates :description, presence: true
  belongs_to :category, optional: true
  has_many :article_notes
  has_many :comments, as: :commentable
  belongs_to :user, optional: true
end

app/controllers/admins/articles_controller.rb
class Admins::ArticlesController < ApplicationController
  load_and_authorize_resource
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to admins_article_path(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to admins_article_path(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admins_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :category_id, :user_id)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show,:download_article_pdf]

  def index
     @articles = Article.all
  end

  def download_article_pdf

  end


  def show

  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admins/articles/_form.html.erb
<%= form_for [:admins, article], :html => { :class => "form-horizontal article" } do |f| %>

  <% if @article.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

   <%= f.hidden_field :user_id, value: current_user.id if user_signed_in? %>
  <div class="form-group">
    <%= f.label :category, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :category_id, options_for_select(Category.all.collect {|p| [ p.name, p.id ] },(f.object.try(:category_id))),{prompt: 'Select Category for Article'},{ :class => 'form-control'} %>
    </div>
    <%=f.error_span(:title) %>
  </div>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control ckeditor' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admins_articles_path, :class => 'btn btn-default' %>
    </div>
  </div>
  <script>
    $(document).ready(function(){
      $('.ckeditor').ckeditor({

      });
    });
  </script>

<% end %>

app/views/admins/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render 'form', article: @article %>

app/views/admins/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, admins_article_path(article) %></td>
        <td><%= article.description.html_safe %></td>
        <td><%=l article.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admins_article_path(article), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admins_article_path(article),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admins_article_path,
            :class => 'btn btn-primary' %>

app/views/admins/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render 'form', article: @article %>

app/views/admins/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @article.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @article.description.html_safe %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admins_articles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admins_article_path(@article), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admins_article_path(@article),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>



<% if @article.article_notes.present? %>
  <div class="well">
    <h2 class="text-center">Notes</h2>
  </div>
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <% @article.article_notes.each do |note| %>
      <div class="panel panel-info">
        <div class="panel-heading" role="tab" id="heading_<%= note.id %>">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse_<%= note.id%>" aria-expanded="false" aria-controls="collapse_<%= note.id%>">
            <h4 class="panel-title">
              <%= note.question %>
            </h4>
          </a>
        </div>
        <div id="collapse_<%= note.id%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_<%= note.id %>">
          <div class="panel-body">
            <%= note.answer.html_safe %>
            <div class="pull-right">
              <%= link_to "Delete This Note", admins_article_article_note_path(@article, note), :class => "btn btn-danger btn-lg", method: :delete, data: {confirm: "Are you sure to delete this article note?"} %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="well">
    <h2 class="text-center">No notes for this article yet!!!</h2>
  </div>
<% end %>

<div class="well">
  <h1 class="text-center">Create Article Notes</h1>
</div>

<%= form_for [:admins, @article, @article.article_notes.build] do |f| %>

  <div class="form-group">
    <%= f.label :question, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :question, :class => 'form-control' %>
    </div>
    <%=f.error_span(:question) %>
  </div>
  <div class="form-group">
    <%= f.label :answer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :answer, :class => 'form-control ckeditor' %>
    </div>
    <%=f.error_span(:answer) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
     <!--  -->
    </div>
  </div>
  <script>
    $(document).ready(function(){
      $('.ckeditor').ckeditor({

      });
    });
  </script>
<% end %>